package_assets:         on          # (on, off, always)
embed_assets:           on          # (on, off, datauri)
compress_assets:        off          # (on, off)
gzip_assets:            on          # (on, off)
template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           packages    # (defaults to assets)
javascript_compressor:  uglifier     # (yui, closure)

javascripts:
  workspace:
    - public/lib/js/underscore.min.js
    - public/lib/js/jquery-1.7.1.min.js
    - public/lib/js/*.js
    - app/views/jst/*.jst
    - public/util/*/*.js

stylesheets:
  workspace:
    - public/lib/css/*.css
