package_assets:         on          # (on, off, always)
embed_assets:           on          # (on, off, datauri)
compress_assets:        off          # (on, off)
gzip_assets:            on          # (on, off)
template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           packages    # (defaults to assets)
javascript_compressor:  uglifier     # (yui, closure)

javascripts:
  common:
    - public/lib/js/underscore.min.js
    - public/lib/js/jquery-1.7.1.min.js
    - public/lib/js/backbone.min.js
    - public/lib/js/humane.min.js
    - public/lib/js/channel.js
    
  workspace:
    - app/views/jst/workspace.jst
    - public/util/views/workspace.js
    
  project:
    - public/lib/js/mac-hud.js
    - public/lib/js/mac-toolbar.js
    - public/lib/js/library.js
    - public/lib/js/project.js

  nodeview:
    - public/lib/js/mac-popup.js
    - public/lib/js/nodeview.js

stylesheets:
  common:
    - public/lib/css/mac-hud.css
    - public/lib/css/mac-button.css
    - public/lib/css/humane-jackedup.css
  
  workspace:
    - public/lib/css/workspace.css

  project:
    - public/lib/css/project.css
    - public/lib/css/mac-toolbar.css

  nodeview:
    - public/lib/css/nodeview.css
    - public/lib/css/mac-popup.css
