package_assets:         on          # (on, off, always)
embed_assets:           on          # (on, off, datauri)
compress_assets:        off          # (on, off)
gzip_assets:            on          # (on, off)
template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           packages    # (defaults to assets)
javascript_compressor:  uglifier     # (yui, closure)

javascripts:
  common:
    - public/lib/js/underscore.min.js
    - public/lib/js/jquery-1.7.1.min.js
    - public/lib/js/backbone.min.js
    - public/lib/js/humane.min.js
    - public/lib/js/channel.js
    
  bootstrap:
    - public/lib/js/bootstrap/bootstrap-twipsy.js
    - public/lib/js/bootstrap/*

  workspace:
    - app/views/jst/workspace.jst
    - public/util/views/workspace.js
    
  project:
    - public/lib/js/mac-hud.js
    - public/lib/js/mac-toolbar.js
    - public/lib/js/library.js
    - public/lib/js/project.js

  nodeview:
    - public/lib/js/mac-popup.js
    - public/util/utils/utils.js
    - public/util/utils/undo_stack.js
    - public/util/tools/*.js
    - public/util/models/rect.js
    - public/util/models/connection.js
    - public/util/models/node.js
    - public/util/models/node_collection.js
    - public/util/models/document.js
    - public/util/views/node_view.js
    - public/util/views/editor_view.js
    - app/views/jst/node.jst
    - public/util/utils/nodeview_setup.js

  codeview:
    - public/util/utils/codeview_setup.js


stylesheets:
  common:
    - public/lib/css/mac-hud.css
    - public/lib/css/mac-button.css
    - public/lib/css/humane-jackedup.css

  bootstrap:
    - public/lib/css/bootstrap.min.css
  
  workspace:
    - public/lib/css/workspace.css

  project:
    - public/lib/css/project.css
    - public/lib/css/mac-toolbar.css

  nodeview:
    - public/lib/css/nodeview.css
    - public/lib/css/mac-popup.css
